package com.devmobile.cs2.esi_lib.DataBasesHandlers;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;

import com.devmobile.cs2.esi_lib.Models.Livre;
import com.devmobile.cs2.esi_lib.R;

import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.Arrays;


public class DataBaseSQLiteHandler extends SQLiteOpenHelper {

    private static final int DATABASE_VERSION = 10;
    private static final String DATABASE_NAME = "bibliodb";
    Context context ;
    private ArrayList<Livre> livre_tous;


    public DataBaseSQLiteHandler(Context context) {
        super(context,DATABASE_NAME,null,DATABASE_VERSION);
        this.context=context ;
    }
    // Au moment du lancement
    @Override
    public void onCreate(SQLiteDatabase db) {
        String create_table_livre = "create table " +
                "livre(id integer primary key,titre text,auteur text,categorie text,annee text,description text,image blob, tags text)";
        db.execSQL(create_table_livre);
        ajouterDesLivre(db);

    }
    // en cas de changement de version et la BDD existe déjà
    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        db.execSQL("DROP TABLE IF EXISTS livre");
        onCreate(db);
    }
   public void ajouterDesLivre(SQLiteDatabase db) {
       // SQLiteDatabase db = this.getWritableDatabase();
       initData();
       for(Livre livre : livre_tous){
           ContentValues contentValues = new ContentValues();
           contentValues.put("titre",livre.getTitre());
           contentValues.put("auteur",livre.getAuteur());
           contentValues.put("categorie",livre.getCategorie());
           contentValues.put("annee",livre.getAnnee());
           contentValues.put("description",livre.getDescription());
           contentValues.put("image",livre.getImage());
           contentValues.put("tags",livre.getTagsString());
           db.insert("livre",null,contentValues);
           //db.close();
       }

   }

   public  ArrayList<Livre> getLivresByCateg(String categ) {
       ArrayList<Livre> livreList = new ArrayList<Livre>();
       String query ="select * from livre where lower(categorie)=?";


       SQLiteDatabase db = this.getReadableDatabase();
       Cursor cursor = db.rawQuery(query, new String[]{categ.toLowerCase()});
       if(cursor.moveToFirst()) {
           do {
               Livre livre = new Livre();
               livre.setId(cursor.getInt(0));
               livre.setTitre(cursor.getString(1));
               livre.setAuteur(cursor.getString(2));
               livre.setCategorie(cursor.getString(3));
               livre.setAnnee(cursor.getString(4));
               livre.setDescription(cursor.getString(5));
               livre.setImage(cursor.getBlob(6));
               livre.setTagsFromString(cursor.getString(7)) ;
               livreList.add(livre);
           }while(cursor.moveToNext());
       }
       db.close();
       return livreList;
   }
    public byte[] getImageByte(Bitmap image) {
        ByteArrayOutputStream stream = new ByteArrayOutputStream();
        image.compress(Bitmap.CompressFormat.PNG,100,stream);
        byte[] imageByte = stream.toByteArray();
        return imageByte;
    }
    public void initData(){
        ArrayList<String> tagsMath = new ArrayList<String>() ;
        ArrayList<String> tagsDefaut = new ArrayList<String>() ;
        tagsMath.add("math");
        tagsMath.add("integrales") ;
        Livre[] livre_tous_table = new Livre[]

                {new Livre(getImageByte(BitmapFactory.decodeResource( context.getApplicationContext().getResources(), R.drawable.math1)), "Analyse numérique", "Eric Canon", "Mathématique", "2012", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés",tagsMath,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.math2)), "Statistiques descriptives", "Luc Lasn", "Mathématique", "2015 ", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.math3)), "Initiation à l'analyse mathématique", "André Giroux", "Mathématique", "2015", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.math4)), "Equations différentielles ordinaires", " Ahmed Lesfari", "Mathématique", "2015", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.math5)), "Probabilités et statistiques appliquées", "Pierre Dreyfuss", "Mathématique", "2004", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.math9)), "Les séries de fonction", "Cédric Villani", "Mathématique", "2003 ", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés",tagsDefaut,0,1),

                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.math6)), "La logique", "Gilles Dowek", "Mathématique", "2003", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.math7)), "Statistiques en sciences humaines avec R", "Jean-Herman Guay", "Mathématique", "2010", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.math8)), "Mathématiques - 1res ES-L", "Thomas Petit", "Mathématique", "1999", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.math9)), "Processus stochastiques", "Sabin Lessard", "Mathématique", "2004", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.math10)), "La maison des mathématiques", "Cédric Villani", "Mathématique", "2003 ", "Est un traité de mathématiques du groupe Nicolas Bourbaki, signé N. Bourbaki et composé de dix livres (divisés chacun en un ou plusieurs chapitres). Les premiers tomes furent publiés par les éditions Hermann à partir de 1940 d'abord sous forme de fascicules, puis sous forme de volumes reliés",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.elec1)), "Les convertisseurs de l'électronique", "Guy Séguier", "Electronique", "2012", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.elec2)), "Bases de l'électronique analogique", "Laurent Pichon", "Electronique", "2015", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.elec3)), "Le grand livre d'Arduino", "Erik Bartmann", "Electronique", "2003", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.elec4)), "Electronique de puissance", "Luc Lasne", "Electronique", "2004", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.elec5)), "Communications sur fibres optiques", "Pierre Lecoy", "Electronique", "2010", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.elec9)), "Electrotechnique", "Fabien Miomandre", "Electronique", "2002", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi",tagsDefaut,0,1),

                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.elec6)), "Réparez vous-même vos appareils électroniques", "Jean Boyer", "Electronique", "2000", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.elec7)), "Optoélectronique appliquée", "Yannick Deshayes", "Electronique", "2001", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.elec8)), "Raspberry Pi", "Maartje Jansee", "Electronique", "1999", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.elec9)), "Electrochimie", "Fabien Miomandre", "Electronique", "2002", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.elec10)), "L'électronique pour les nuls", "Gordon McComb", "Electronique", "1998", "Besoins pour tes équipements courants et les besoins en puissance pour les gros appareils ménagers, le chauffage électrique et l'eau chaude sanitaire. Les énergies renouvelables, la cogénération, l'énergie solaire photovoltaïque et l'énergie éolienne sont aussi",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.algo1)), "Construire des robots très simples", "H. Katzenmaier", "Algorithmique", "2000", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.algo2)), "Algorithmique", "Collectif Dunod", "Algorithmique", "2001", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.algo3)), "Algorithmique et programmation en Java", "Vincent Granet", "Algorithmique", "2015", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.algo4)), "Programmer pour les nuls", "Wallace Wang", "Algorithmique", "2012", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.algo5)), "L'intelligence artificielle pour les développeurs", " Virginie Mathivet", "Algorithmique", "2013", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.algo9)), "Astuces de programmation", "Sébastien Rohaut", "Algorithmique", "1992", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème.",tagsDefaut,0,1),

                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.algo6)), "Cours d'algèbre et d'algorithmique", "Pierre Meunier", "Algorithmique", "2004", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème.",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.algo7)), "Mathématiques et informatique", "Collectif Tangente", "Algorithmique", "2000", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème.",tagsDefaut,0,1),
                       //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.algo8)), "Initiation à l'algorithmique et à la programmation en C", "Rita Zrour", "Algorithmique", "2009", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème.",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.algo9)), "Techniques fondamentales de programmation", "Sébastien Rohaut", "Algorithmique", "1992", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème.",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.algo10)), "Algorithmes et théorie des nombres", "Pierre Audibert", "Algorithmique", "1999", "L'algorithmique est l'étude et la production de règles et techniques qui sont impliquées dans la définition et la conception d'algorithmes, c'est-à-dire de processus systématiques de résolution d'un problème permettant de décrire les étapes vers le résultat. En d'autres termes, un algorithme est une suite finie et non-ambiguë d’instructions permettant de donner la réponse à un problème.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.base1)), "Les bases de données NoSQL", " Rudi Bruchez", "Base de donnée", "1999", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.base2)), "Merise", "Jean-Luc Baptiste", "Base de donnée", "2004", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.base3)), "UML et XML pour le commerce électronique", "Odile Troulet-Lambert", "Base de donnée", "2005", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.base4)), "SQL pour Oracle", "Christian Soutou", "Base de donnée", "2013", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.base5)), "PostgreSQL", " Sébastien Lardière", "Base de donnée", "2015", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.base9)), "Big Data", "Marc Batty", "Base de donnée", "1994", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé.",tagsDefaut,0,1),

                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.base6)), "Access 2013", "Pierre Rigollet", "Base de donnée", "2003", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé.",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.base7)), "SQL Server 2014", "Olivier Maitre", "Base de donnée", "2015", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé.",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.base8)), "Oracle 12c", "Olivier Heurtel", "Base de donnée", "2003", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé.",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.base9)), "Big Data et Machine Learning", "Marc Batty", "Base de donnée", "1994", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé.",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.base10)), "Apprentissage machine", "Massih-Reza Amini", "Base de donnée", "1997", "Une base de données (en anglais : database) est un outil permettant de stocker et de retrouver l'intégralité de données brutes ou d'informations en rapport avec un thème ou une activité ; celles-ci peuvent être de natures différentes et plus ou moins reliées entre elles1,2. Dans la très grande majorité des cas, ces informations sont très structurées, et la base est localisée dans un même lieu et sur un même support. Ce dernier est généralement informatisé.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.si1)), "Ingénierie des exigences", "Stéphane Badreau", "Système d'information", "2004", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.si2)), "Processus métiers et S.I.", "Chantal Morley", "Système d'information", "2005", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.si3)), "Expression des besoins pour le SI", "Yves Constantinidis", "Système d'information", "2003", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.si4)), "Business Intelligence et management", "Alphonse Carlier", "Système d'information", "2005", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.si5)), "Management des systèmes d'information", "Sylvie Gerbaix, Marc Pasquet", "Système d'information", "2009", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence.",tagsDefaut,0,1),
                        new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.si9)), "Cloud SaaS", "Jean-Louis Caire", "Système d'information", "1995", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence.",tagsDefaut,0,1),

                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.si6)), "Business intelligence", "Jean-Pierre Girardot", "Système d'information", "1995", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence.",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.si7)), "Optimiser l'organisation informatique de la PME", "Yves Le Dain", "Système d'information", "1990", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence.",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.si8)), "Yves Le Dain", "Oihab Allal-Chérif", "Système d'information", "2013", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence.",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.si9)), "Objectif Cloud", "Jean-Louis Caire", "Système d'information", "1995", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence.",tagsDefaut,0,1),
                        //new Livre(getImageByte(BitmapFactory.decodeResource(context.getResources(), R.drawable.si10)), "Le cloud computing", "Bénédicte Fauvarque", "Système d'information", "19964", "La gouvernance des Systèmes d'Information orientée chaîne de valeurs IT. En un peu plus de 400 pages, Charles Betz replace le focus sur le rôle essentiel du système d'information dans la chaîne de valeurs globale de l'entreprise. Ainsi les briques technologiques et les cadres de mise en oeuvre comme COBIT, ITIL et CMM s'intègrent en parfaite cohérence.",tagsDefaut,0,1),
                };
        livre_tous =  new ArrayList<Livre>(Arrays.asList(livre_tous_table)) ;
    }
}
